Document: bu
Title: Debian bu Manual
Author: <insert document author here>
Abstract: This manual describes what bu is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/bu/bu.sgml.gz

Format: postscript
Files: /usr/share/doc/bu/bu.ps.gz

Format: text
Files: /usr/share/doc/bu/bu.text.gz

Format: HTML
Index: /usr/share/doc/bu/html/index.html
Files: /usr/share/doc/bu/html/*.html

  
